import { isProxy, toRaw } from 'vue'
import type { ServiceRecord, Displacement } from '~/stores/services'
import type { ExpenseRecord } from '~/stores/expenses'
import type { ExpenseCategory } from '~/utils/expenseCategories'

// Minified interfaces for QR payload
interface MinifiedDisplacement {
    p: string // province
    m: string // municipality
    l?: 1 // hasLunch (1 if true, undefined if false)
    d?: 1 // hasDinner (1 if true, undefined if false)
    o?: string // observations
}

interface MinifiedServiceRecord {
    s: string // startTime
    e: string // endTime
    k?: number // kilometers
    n?: string // notes
    d: MinifiedDisplacement[] // displacements
}

/**
 * Compresses a ServiceRecord into a minified object for QR code generation.
 * Removes IDs and uses short keys.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const compressServiceRecord = (record: any): MinifiedServiceRecord => {
    // Handle both reactive objects and plain objects
    const src = isProxy(record) ? toRaw(record) : record

    return {
        s: src.startTime,
        e: src.endTime,
        k: src.kilometers,
        n: src.notes || undefined,
        d: src.displacements.map((d: Displacement) => {
            const minDisp: MinifiedDisplacement = {
                p: d.province,
                m: d.municipality
            }
            if (d.hasLunch) minDisp.l = 1
            if (d.hasDinner) minDisp.d = 1
            if (d.observations) minDisp.o = d.observations
            return minDisp
        })
    }
}

/**
 * Decompresses a minified object (or legacy full object) back into a partial ServiceRecord.
 * IDs are NOT generated here, they should be generated by the consumer (e.g. creating new UUIDs).
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const decompressServiceRecord = (data: any): Partial<ServiceRecord> => {
    // Check if it's the legacy format (has 'startTime' property)
    if (data.startTime && Array.isArray(data.displacements)) {
        return data as Partial<ServiceRecord>
    }

    // Assume minified format
    const minified = data as MinifiedServiceRecord

    return {
        startTime: minified.s,
        endTime: minified.e,
        kilometers: minified.k,
        notes: minified.n || '',
        displacements: Array.isArray(minified.d) ? minified.d.map(md => ({
            id: '', // Placeholder, should be regenerated
            province: md.p,
            municipality: md.m,
            hasLunch: md.l === 1,
            hasDinner: md.d === 1,
            observations: md.o || ''
        })) : []
    }
}

// Minified expense payload for QR. The ticket attachment is intentionally
// omitted — receipt images are far too large to fit in a QR code.
interface MinifiedExpense {
    d: string // description
    a: number // amount
    t: string // timestamp (UTC ISO)
    c?: ExpenseCategory // category
}

/**
 * Compresses an ExpenseRecord into a minified object for QR code generation.
 * Drops the id and any attached ticket.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const compressExpenseRecord = (record: any): MinifiedExpense => {
    const src = isProxy(record) ? toRaw(record) : record
    return {
        d: src.description,
        a: src.amount,
        t: src.timestamp,
        c: src.category || undefined
    }
}

/**
 * Decompresses a minified object (or legacy full object) into a partial
 * ExpenseRecord. The id is NOT generated here.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const decompressExpenseRecord = (data: any): Partial<ExpenseRecord> => {
    // Legacy/full format carries the long property names.
    if (data.description !== undefined && data.timestamp !== undefined) {
        return {
            description: data.description,
            amount: data.amount,
            timestamp: data.timestamp,
            category: data.category
        }
    }

    const minified = data as MinifiedExpense
    return {
        description: minified.d,
        amount: minified.a,
        timestamp: minified.t,
        category: minified.c
    }
}
