import { isProxy, toRaw } from 'vue'
import type { ServiceRecord, Displacement } from '~/stores/services'

// Minified interfaces for QR payload
interface MinifiedDisplacement {
    p: string // province
    m: string // municipality
    l?: 1 // hasLunch (1 if true, undefined if false)
    d?: 1 // hasDinner (1 if true, undefined if false)
    o?: string // observations
}

interface MinifiedServiceRecord {
    s: string // startTime
    e: string // endTime
    k?: number // kilometers
    n?: string // notes
    d: MinifiedDisplacement[] // displacements
}

/**
 * Compresses a ServiceRecord into a minified object for QR code generation.
 * Removes IDs and uses short keys.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const compressServiceRecord = (record: any): MinifiedServiceRecord => {
    // Handle both reactive objects and plain objects
    const src = isProxy(record) ? toRaw(record) : record

    return {
        s: src.startTime,
        e: src.endTime,
        k: src.kilometers,
        n: src.notes || undefined,
        d: src.displacements.map((d: Displacement) => {
            const minDisp: MinifiedDisplacement = {
                p: d.province,
                m: d.municipality
            }
            if (d.hasLunch) minDisp.l = 1
            if (d.hasDinner) minDisp.d = 1
            if (d.observations) minDisp.o = d.observations
            return minDisp
        })
    }
}

/**
 * Decompresses a minified object (or legacy full object) back into a partial ServiceRecord.
 * IDs are NOT generated here, they should be generated by the consumer (e.g. creating new UUIDs).
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const decompressServiceRecord = (data: any): Partial<ServiceRecord> => {
    // Check if it's the legacy format (has 'startTime' property)
    if (data.startTime && Array.isArray(data.displacements)) {
        return data as Partial<ServiceRecord>
    }

    // Assume minified format
    const minified = data as MinifiedServiceRecord

    return {
        startTime: minified.s,
        endTime: minified.e,
        kilometers: minified.k,
        notes: minified.n || '',
        displacements: Array.isArray(minified.d) ? minified.d.map(md => ({
            id: '', // Placeholder, should be regenerated
            province: md.p,
            municipality: md.m,
            hasLunch: md.l === 1,
            hasDinner: md.d === 1,
            observations: md.o || ''
        })) : []
    }
}
